# Draft signed into law
PREFIX :   <https://id.parliament.uk/schema/>
SELECT DISTINCT ?workPackage WHERE {
  ?workPackage a :WorkPackage ; :workPackagedThing ?thing .
  ?thing a :StatutoryInstrument .
  ?bi a :BusinessItem ; :workPackagedThing ?thing ; :businessItemHasProcedureStep ?step .
  ?step :preferredLabel ?label .
  FILTER ( CONTAINS(LCASE(?label), "signed into law") )
}