# procedure-steps-all.sparql: get timeline steps for all WPs since ?since
PREFIX :    <https://id.parliament.uk/schema/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX id:  <https://id.parliament.uk/>

SELECT DISTINCT ?workPackage ?step ?stepLabel ?date ?houseLabel
WHERE {
  ?si a :StatutoryInstrumentPaper ;
      :workPackagedThingHasWorkPackage ?workPackage .

  ?workPackage :workPackageHasBusinessItem ?bi .
  ?bi :businessItemDate ?date ;
      :businessItemHasProcedureStep ?step .
  OPTIONAL { ?step rdfs:label ?stepLabel . }
  OPTIONAL { ?bi :businessItemHasHouse ?house . ?house :preferredLabel ?houseLabel . }

  FILTER (?date >= ?since)
}
ORDER BY ?workPackage ?date
