name: Probe Parliament SPARQL (diagnostics)

on:
  workflow_dispatch:

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run diagnostics probe
        run: node apps/si-tracker-v2.1/scripts/diagnostic-probe.mjs

      - name: Commit probe results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update diagnostics probe output"
          file_pattern: "apps/si-tracker-v2.1/data/probe.json"
